### ISSUE TITLE
Feature suggestion: ignore if downloaded

### ISSUE THREAD

**Issue by wamatt** [jamesridgway/attachment-downloader#23]
Might be nice to allow option to not ignore existing files. This way one can run the script idempotently, and only new files will be added.

A nice side effect is it save bandwidth, keeps file dates in chronological order (like if you're running a daily chron job), and also doesn't trigger any file watching logic on the OS side.

**Comment by jamesridgway** [comment]
Please feel free to raise a pull request to add this feature :)
