### ISSUE TITLE
Feature suggestion: Allow relative dates

### ISSUE THREAD

**Issue by wamatt** [jamesridgway/attachment-downloader#24]
Firstly, thank you for a fantastic tool. :)

Anyways this proposed feature would allow one to specify a relative time, eg "2 Months Ago" which would be a rolling window. That way additional client side logic is not needed if you run the task periodically and only want to process newish mails for performance reasons.

**Comment by jamesridgway** [comment]
Please feel free to create a pull request to add this feature.

**Comment by KottV** [comment]
It can be achieved by inserting command output as argument:
```
--date-after=`date -d '1 hour ago' -I'seconds'`
```

thank you for a great tool!
