### ISSUE TITLE
can't access attachment from GMAIL subfolder 

### ISSUE THREAD

**Issue by rizpythonista** [jamesridgway/attachment-downloader#28]
"attachment-downloader --host imap.gmail.com --username abdullahakhtar354@gmail.com --password XXXXXXXX --imap-folder inbox --output ~\Desktop\F-ass"
 I tried this code but always it open the source code in next file but not download the attachment

**Comment by jamesridgway** [comment]
I have no idea what you mean by this:

> I tried this code but always it open the source code in next file but not download the attachment


Can you confirm:
* How are you running the tool?
* What operating system are you using?
* Can you provide the actual output/logs shown by the tool when you try and run it?
*
