### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by idcline** [jamesridgway/attachment-downloader#35]
Used pip install attachment-downloader to install and received error.

pi@raspberrypi:~ $ pip install attachment-downloader
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting attachment-downloader
  Downloading https://files.pythonhosted.org/packages/1f/6f/2b07c1ccc7d009a039fbf7cb1173ae06f0d58ba9266a7c1494a6826ea9b0/attachment-downloader-1.2.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-7GnDBu/attachment-downloader/setup.py", line 5, in <module>
        from attachment_downloader.version_info import Version
      File "attachment_downloader/version_info.py", line 17
        file.write(f'ATTACHMENT_DOWNLOADER_VERSION = "{version}"\n')
                                                                  ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-7GnDBu/attachment-downloader/

**Comment by jamesridgway** [comment]
Hi,

Please can you let me know:

- python version
- pip version
- operating system and version

**Comment by idcline** [comment]
My bad, I should have check for that first.  I am using Python Python 2.7.16, pip 18.1 from /usr/lib/python2.7/dist-packages/pip (python 2.7), Raspbian GNU/Linux 10 (buster)

The PicFrame requires buster.  I will have to see if I can upgrade to Python 3+ without breaking PicFrame

**Comment by idcline** [comment]
Python 3 version is installed, Python 3.7.3

> Begin forwarded message:
> 
> From: David Cline ***@***.***>
> Subject: Re: [jamesridgway/attachment-downloader] Install error (Issue #35)
> Date: April 17, 2022 at 1:57:46 PM GMT+1
> To: jamesridgway/attachment-downloader ***@***.***>
> 
> My bad, I should have check for that first.  I am using Python Python 2.7.16, pip 18.1 from /usr/lib/python2.7/dist-packages/pip (python 2.7), Raspbian GNU/Linux 10 (buster)
> 
> The PicFrame requires buster.  I will have to see if I can upgrade to Python 3+ without breaking PicFrame
> 
>

**Comment by idcline** [comment]
Correct installation is

 python3 -m pip install attachment-downloader, I was using 

 pip install attachment-downloader
