### ISSUE TITLE
Install won't work anymore

### ISSUE THREAD

**Issue by sapnho** [jamesridgway/attachment-downloader#40]
Hi James, I was alerted by a few people (and just tried it myself) that the `pip install attachment-downloader` command results in a `Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-IFS025/attachment-downloader/` message.

I just tested it with Buster on a Pi4. Has anything changed that has come to your attention?

**Comment by sapnho** [comment]
Ah, just tried `pip3` that did the trick!

**Comment by jamesridgway** [comment]
Hi @sapnho - glad you figured out the issue.

The readme cover the requirements of Python 3 which will hopefully prevent anyone else fallign into the same trap
https://github.com/jamesridgway/attachment-downloader#requirements
