### ISSUE TITLE
Loglevel

### ISSUE THREAD

**Issue by geimist** [jamesridgway/attachment-downloader#44]
Is there a way to influence the log level? I would like to output only everything from "Warning".
Thank you.

**Comment by jamesridgway** [comment]
In 1.2.5 you can now customise the log level using the `--log-level` argument,

E.g.
```
--log-level INFO
```

Values:
```
Set the log level to DEBUG, INFO, WARNING, ERROR, or CRITICAL (default is INFO)
```
