### ISSUE TITLE
Dependency errors when installing pip

### ISSUE THREAD

**Issue by christoph2307** [jamesridgway/attachment-downloader#59]
I have tried to install this tool and it throws errors when using the provided scripts. This happens in WSL for Windows 11 and Ubuntu, both with a clean install and also in venv. For example this error is thrown:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
styletts2 0.1.6 requires gruut<3.0.0,>=2.3.4, but you have gruut 2.2.3 which is incompatible.
styletts2 0.1.6 requires librosa<0.11.0,>=0.10.1, but you have librosa 0.10.0 which is incompatible.
styletts2 0.1.6 requires transformers<5.0.0,>=4.36.0, but you have transformers 4.30.0 which is incompatible.
```
It seems that the provided requirements.txt is broken.

**Comment by jamesridgway** [comment]
A newer version of the library - 1.2.8 has been released which includes updated dependencies, please give this a try as this should resolve the issue.
